name: Wheel build

on: [push]

jobs:
  build-wheel:
    name: Build ${{ matrix.platform }} wheels
    runs-on: ubuntu-latest
    strategy:    
      matrix:
        platform:
          - manylinux1_x86_64
          - manylinux1_i686
          - manylinux2014_x86_64
          - manylinux2014_aarch64
        python-version:
          # the versions are <python tag>-<abi tag> as specified in PEP 425.
          - cp36-cp36m
          - cp37-cp37m
          - cp38-cp38
          - cp39-cp39  
        
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up QEMU
      if: ${{ matrix.platform == 'manylinux2014_aarch64' }}
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.py-ver }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy pytest pyyaml make cmake
    - name: Build manylinux Python wheels
      if: ${{ matrix.platform == 'manylinux1_x86_64' }}
      uses: RalfG/python-wheels-manylinux-build@v0.3.4-manylinux1_x86_64
      with:
        python-versions: 'cp36-cp36m cp37-cp37m cp38-cp38 cp39-cp39'
        pre-build-command: cp -a ../src .
        package-path: ./python
    - name: Build manylinux Python wheels
      if: ${{ matrix.platform == 'manylinux1_i686' }}
      uses: RalfG/python-wheels-manylinux-build@v0.3.4-manylinux1_i686
      with:
        python-versions: 'cp36-cp36m cp37-cp37m cp38-cp38 cp39-cp39'
        pre-build-command: cp -a ../src .
        package-path: ./python
    - name: Build manylinux Python wheels
      if: ${{ matrix.platform == 'manylinux2014_x86_64' }}
      uses: RalfG/python-wheels-manylinux-build@v0.3.4-manylinux2014_x86_64
      with:
        python-versions: ${{ matrix.py-ver }}
        pre-build-command: cp -a ../src .
        package-path: ./python
    - name: Build manylinux Python wheels
      if: ${{ matrix.platform == 'manylinux2014_aarch64' }}
      uses: RalfG/python-wheels-manylinux-build@v0.3.4-manylinux2014_aarch64
      with:
        python-versions: ${{ matrix.py-ver }}
        pre-build-command: cp -a ../src .
        package-path: ./python
        
    - name: Check created wheel
      run: |
        export PATH=/opt/python/${{ matrix.py-ver }}/bin:$PATH &&
        pip install -f python/dist spglib
        cd python
        pytest
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: ./python/dist/*-manylinux*.whl
